DROP DATABASE IF NOT EXISTS test;
CREATE DATABASE test DEFAULT CHARACTER SET utf8;
use test;

CREATE TABLE post (
	id INT AUTO_INCREMENT PRIMARY KEY,	
	title VARCHAR(64) NOT NULL UNIQUE,	
	content VARCHAR(960) NULL,
	created DATETIME NOT NULL
);
