DROP DATABASE IF EXISTS `blog`;
CREATE DATABASE `blog`;
USE `blog`;

CREATE TABLE post (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(320) NOT NULL,
	`content` TEXT NOT NULL,
	`author` VARCHAR(160) NOT NULL,
	`created` DATE NOT NULL,
	`updated` DATE NULL
);
