language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
  - mysql -e 'CREATE DATABASE blog;'
  - mysql -e 'USE `blog`;DROP TABLE IF EXISTS `post`;CREATE TABLE post (`id` INT AUTO_INCREMENT PRIMARY KEY,`title` VARCHAR(320) NOT NULL,`content` TEXT NOT NULL,`author` VARCHAR(160) NOT NULL,`created` DATE NOT NULL,`updated` DATE NULL);'
